language: python
dist: trusty
python:
   - "2.7"
   - "3.4"
   - "3.5"
   - "3.6"
before_install:
  - sudo apt-get update
install:
  - "pip install numpy scipy matplotlib pytest"
script:
  - py.test -vv -s
notifications: 
  email: false
